Repository vapor/fluent-mysql-driver, pull requests merged in 2018-02, with the labels that each got.

#70 Release candidate update
  Package.swift
  Sources/FluentMySQL/MySQLDatabase.swift
  Tests/FluentMySQLTests/FluentMySQLTests.swift
  circle.yml
Labels: bug, enhancement

#75 sql logger + test fixes
  LICENSE
  README.md
  Sources/FluentMySQL/FluentMySQLProvider.swift
  Sources/FluentMySQL/MySQLConnection.swift
  Sources/FluentMySQL/MySQLConnectionConfig.swift
  Sources/FluentMySQL/MySQLDatabase+Query.swift
  Sources/FluentMySQL/MySQLDatabase+Schema.swift
  Sources/FluentMySQL/MySQLDatabase.swift
  circle.yml
Labels: bug

#49 fluent mysql beta
  .circleci/config.yml
  .gitignore
  LICENSE
  Package.swift
  README.md
  Sources/FluentMySQL/Exports.swift
  Sources/FluentMySQL/FluentMySQLProvider.swift
  Sources/FluentMySQL/Logger.swift
  Sources/FluentMySQL/MySQL+FieldTypes.swift
  Sources/FluentMySQL/MySQLConnection.swift
  Sources/FluentMySQL/MySQLDatabase+Query.swift
  Sources/FluentMySQL/MySQLDatabase+Schema.swift
  Sources/FluentMySQL/MySQLDatabase+Transaction.swift
  Sources/FluentMySQL/MySQLDatabase.swift
  Sources/MySQLDriver/Creator+MySQLTypes.swift
  Sources/MySQLDriver/MySQLConnection.swift
  Sources/MySQLDriver/MySQLDriver.swift
  Sources/MySQLDriver/MySQLSerializer.swift
  Tests/FluentMySQLTests/FluentMySQLTests.swift
  Tests/LinuxMain.swift
  Tests/MySQLDriverTests/FluentMySQLTests.swift
  Tests/MySQLDriverTests/Utilities/MySQLDriver+Tests.swift
  circle.yml
Labels: enhancement
