Repository vapor/fluent-mysql-driver, pull requests merged in 2020-05, with the labels that each got.

#173 Makes `isConstraintFailure` return true on duplicate constraint failure.
  Sources/FluentMySQLDriver/MySQLError+Database.swift
Labels: bug, semver-patch

#175 Register Multiple Databases for FluentBenchmarker Tests
  .github/workflows/test.yml
  Tests/FluentMySQLDriverTests/FluentMySQLDriverTests.swift
Labels: bug

#178 FluentKit 1.0.0 GM
  .github/workflows/test.yml
  Package.swift
  Sources/FluentMySQLDriver/FluentMySQLDatabase.swift
  Sources/FluentMySQLDriver/FluentMySQLDriver.swift
  Sources/FluentMySQLDriver/MySQLConverterDelegate.swift
  Sources/FluentMySQLDriver/MySQLRow+Database.swift
  Tests/FluentMySQLDriverTests/FluentMySQLDriverTests.swift
  docker-compose.yml
Labels: enhancement, semver-major

#179 Make the tests run with more threads
  Tests/FluentMySQLDriverTests/FluentMySQLDriverTests.swift
Labels: enhancement
